language: csharp

os: linux

sudo: required
dist: bionic

dotnet: 2.2.203
mono: latest

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

addons:
  ssh_known_hosts: github.com

before_install:
  - chmod +x travis/fix-branches.sh
  - "./travis/fix-branches.sh"

install:
  - dotnet tool install -g Cake.Tool --version 0.33.0

before_script:
  - PATH=$PATH:/home/travis/.dotnet/tools

script:
  - dotnet-cake --target="Travis"

cache:
  directories:
    - tools
    - $HOME/.nuget/packages
